# 【超初心者向け】Numpy基礎50本ノック

https://qiita.com/moe_713/items/671c8c912f6e8d6c7442?fbclid=IwAR02kecyHTdg8psjwYgveBXLbv9fYoUMxTlFQPV4Yyahi9cVWWcGEn82Q-U

In [1]:
import numpy as np

## 5. 配列の演算

### 36. np.sum  
配列の要素の合計値  
a = np.array([[1, 2, 3],[4,5,6]])   
の全要素の合計、列ごとの合計値をそれぞれ出せ。

In [2]:
a = np.array([[1, 2, 3],[4,5,6]])
np.sum(a)

21

In [3]:
np.sum(a, axis=0) #列ごとの合計値

array([5, 7, 9])

In [4]:
np.sum(a, axis=1) #列ごとの合計値

array([ 6, 15])

### 37. np.multiply(a, b)  
a, bの要素ごとの積（アダマール積）  
公式ドキュメント：https://numpy.org/doc/stable/reference/generated/numpy.multiply.html  
a = np.array([1, 2, 3])  
b = np.array([4, 5, 6])  
a と b の要素ごとの積を計算せよ。

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.multiply(a,b)

array([ 4, 10, 18])

In [6]:
# ＊operator と同じ役割をする
a * b

array([ 4, 10, 18])

### 38. np.dot(a, b)    
a, bの配列同士の積  
公式ドキュメント：https://numpy.org/doc/stable/reference/generated/numpy.dot.html  
a = np.arange(3).reshape(1, 3)
b = np.arange(3).reshape(3, 1)
a と b の配列同士の積を求めよ。

In [7]:
a = np.arange(3).reshape(1, 3)
b = np.arange(3).reshape(3, 1)
print(a)
print(b)

[[0 1 2]]
[[0]
 [1]
 [2]]


In [8]:
np.dot(a,b)

array([[5]])

In [9]:
# 引数が両方とも一次元配列の場合は内積を返す
a = np.array([1,2])
b = np.array([3,4])
np.dot(a,b)

11

In [10]:
# 虚数計算の例
np.dot([2, 1+3j], [4, 2+3j])

(1+9j)

### 39. np.mean  
平均の算出  
a = np.arange(10).reshape(2, 5)
a の平均値を求めよ。

In [11]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
np.mean(a)

4.5

### 40. np.std
標準偏差の算出  
a = np.arange(10).reshape(2, 5)
a の標準偏差を求めよ。

In [13]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
np.std(a)

2.8722813232690143