# 【超初心者向け】Numpy基礎50本ノック

https://qiita.com/moe_713/items/671c8c912f6e8d6c7442?fbclid=IwAR02kecyHTdg8psjwYgveBXLbv9fYoUMxTlFQPV4Yyahi9cVWWcGEn82Q-U

In [2]:
import numpy as np

## 3. 配列の参照をする

### 16. ndarray.dtype  
a = np.array([[1, 2 ,3],[4, 5, 6]]) の要素の型を参照しろ。

In [3]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.dtype

dtype('int32')

In [6]:
a = np.array([[1.0, 2.0 ,3.0],[4.0, 5.0, 6.0]])
a.dtype

dtype('float64')

In [7]:
a = np.array([["1", "2" ,"3"],["4", "5", "6"]])
a.dtype

dtype('<U1')

In [9]:
# 複数の要素が入っている場合
a = np.array([1, 2.0 ,3])
a.dtype
# int型とfloat型が混在しているときは float型になる

dtype('float64')

In [10]:
a = np.array([1, 2.0 ,"3"])
a.dtype
# 文字列が入っていると文字列型になる

dtype('<U32')

In [8]:
# Numpy のデータタイプ：https://note.nkmk.me/python-numpy-dtype-astype/
# U は Unicode文字列
# 先頭の<, >は、それぞれリトルエンディアン、ビッグエンディアンを表している。
# ほとんどの場合、特に気にする必要はない
# U の後の数字はメモリーで確保している文字数
# 

### 17. [p, q]   
配列のp行q列目の要素の参照  

In [11]:
a = np.array([1, 2, 3])
a[1] # 先頭を0番目とした際の1番目の値を参照

2

In [12]:
a[0:2] # 0番目から、２番目の一つ手前までを参照

array([1, 2])

In [13]:
b = np.array([[1, 2 ,3],[4, 5, 6]])
b[0,1] # 0行1列目を参照

2

In [14]:
b[:,1] # 1列目を参照

array([2, 5])

In [15]:
b[:,[1,2]] # 1,2列目を参照

array([[2, 3],
       [5, 6]])

In [ ]:
# なお、コロンを用いてリストや文字列の一部を参照したり取り出すことができることをスライスと呼びます。

In [46]:
# ２次元の場合のルールは Pandas の iloc() と同じですね。
import pandas as pd
df = pd.DataFrame(b)
df

0  1  2
0  1  2  3
1  4  5  6

In [47]:
df.iloc[0,1]  # 0行1列目を参照

2

In [49]:
pd.DataFrame(df.iloc[:,1]) # 1列目を参照

1
0  2
1  5

In [50]:
df.iloc[:,[1,2]] # 1,2列目を参照

1  2
0  2  3
1  5  6

## 4. 配列を操作する

### 18. ndarray.reshape(p, q)  
p行q列の配列に変換  
a = np.array([[1, 2 ,3],[4, 5, 6]]) を２行３列に変換しろ。

In [58]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.reshape(3, 2) # 変換後の戻り値を返す

array([[1, 2],
       [3, 4],
       [5, 6]])

In [59]:
a # 元の配列はそのまま

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
# 行か列を -1 にすると、指定している行が列に合わせて他方を自動計算してくれる
a.reshape(-1, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
a.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

### 19. ndarray.resize(p, q) 
p行q列の配列に変換し、変更された配列がもとの配列より大きければ、必要なだけ0で埋める  
a = np.array([[1, 2 ,3],[4, 5, 6]]) を３行３列に変換しろ。足りない要素は0で埋めろ。

In [60]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.resize(3, 3) # reshape()と違って戻り値を返さずに変数を上書きする

In [61]:
a # 変数 a は上書きされている

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0]])

### 20. ndarray.ravel
多次元配列を1次元の行列にする  
a = np.array([[1, 2 ,3],[4, 5, 6]]) を１次元の行列にしろ。

In [62]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.ravel() # a は上書きされない

array([1, 2, 3, 4, 5, 6])

In [63]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
# なお、ndarray.flattenでも同じ事ができますが、ravelの方がより高速に処理できることがあるそう。
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [65]:
a # flatten() も上書きされない

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
# 戻り値を返して元の配列が上書きされないときは、同じ変数を上書きするか別の変数に代入する場合が多い
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6])