# 【超初心者向け】Numpy基礎50本ノック

https://qiita.com/moe_713/items/671c8c912f6e8d6c7442?fbclid=IwAR02kecyHTdg8psjwYgveBXLbv9fYoUMxTlFQPV4Yyahi9cVWWcGEn82Q-U

In [1]:
import numpy as np

## 4. 配列を操作する

### 26. np.any   
配列の要素のいずれかが条件を満たすか否かを判定する    
    a = np.arange(6).reshape((2, 3)) のいっずれかの条件が a < 6 を満たすか判定しろ。

In [2]:
a = np.arange(6).reshape((2, 3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [3]:
np.any(a < 6)

True

In [4]:
np.any(a > 6)

False

### 27. ndarray.argmax   
多次元配列の中の最大値の要素を持つインデックスを返す    
    a = np.array([1, 2, 3]) の最大値を返せ。

In [5]:
a = np.array([1, 2, 3])
a.argmax()

2

### 28. np.sort
https://numpy.org/doc/stable/reference/generated/numpy.sort.html  
https://qiita.com/moe_713/items/671c8c912f6e8d6c7442?fbclid=IwAR02kecyHTdg8psjwYgveBXLbv9fYoUMxTlFQPV4Yyahi9cVWWcGEn82Q-U  
配列を小さい順に並べ替える
    a = np.array([8, 2, 1, 5, 6]) を（１）昇順および（２）降順で並べ替えろ

In [6]:
# (1) 昇順
a = np.array([8, 2, 1, 5, 6])
np.sort(a)

array([1, 2, 5, 6, 8])

In [7]:
# (2) 降順
np.sort(a)[::-1] # 降順は[::-1]を後ろにつける

array([8, 6, 5, 2, 1])

In [8]:
# 公式ドキュメントのコード例
a = np.array([[1,4],[3,1]])
a

array([[1, 4],
       [3, 1]])

In [9]:
np.sort(a)                # sort along the last axis

array([[1, 4],
       [1, 3]])

In [10]:
np.sort(a, axis=None)     # sort the flattened array

array([1, 1, 3, 4])

In [11]:
np.sort(a, axis=0)        # sort along the first axis

array([[1, 1],
       [3, 4]])

### 29. np.argsort
配列を小さい順に並べ替えた際の配列のインデックスを出力  
    a = np.array([8, 2, 1, 5, 6])を（１）昇順および（２）降順で並べ替えた際のインデックスを求めろ

In [12]:
a = np.array([8, 2, 1, 5, 6])

In [13]:
# (1) 昇順
np.sort(a)

array([1, 2, 5, 6, 8])

In [14]:
np.argsort(a)

array([2, 1, 3, 4, 0], dtype=int64)

In [15]:
# (2) 降順
np.sort(a)[::-1]

array([8, 6, 5, 2, 1])

In [16]:
np.argsort(a)[::-1] # 降順は[::-1]を後ろにつける

array([0, 4, 3, 1, 2], dtype=int64)

### 30. np.expand_dims
配列に次元を追加  
    a = np.arange(6).reshape(2, 3)の次元をインデックスを３通りで増やせ

In [17]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
a.shape

(2, 3)

In [19]:
np.expand_dims(a, 0)

array([[[0, 1, 2],
        [3, 4, 5]]])

In [20]:
np.expand_dims(a, 0).shape

(1, 2, 3)

In [21]:
np.expand_dims(a, 1)

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [22]:
np.expand_dims(a, 1).shape

(2, 1, 3)

In [23]:
np.expand_dims(a, 2)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [24]:
np.expand_dims(a, 2).shape

(2, 3, 1)