# 【超初心者向け】Numpy基礎50本ノック

https://qiita.com/moe_713/items/671c8c912f6e8d6c7442?fbclid=IwAR02kecyHTdg8psjwYgveBXLbv9fYoUMxTlFQPV4Yyahi9cVWWcGEn82Q-U

In [1]:
import numpy as np

## 4. 配列を操作する

### 31. np.broadcast_to   
ブロードキャストと呼ばれる、異なる形状の配列を自動統一を実施  
特にbroadcast_toは配列を任意の形状にブロードキャストする際に使用する  
a = np.arange(2) を２つの要素を最小単位単位にもつ３次元行列にしろ。

In [2]:
a = np.arange(2)
print(a)
np.broadcast_to(a,(3,2))

[0 1]


array([[0, 1],
       [0, 1],
       [0, 1]])

公式ドキュメント：https://numpy.org/doc/stable/reference/generated/numpy.broadcast_to.html  

In [3]:
x = np.array([1, 2, 3])
np.broadcast_to(x, (3, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### 32. np.broadcast_arrays  
複数の配列をブロードキャストして形状を揃えたい際に使用する  
a = np.arange(3)  
b = np.arange(3).reshape(3, 1)  
np.broadcast_arrays(a, b)  
を実行せよ。

In [4]:
a = np.arange(3)
print(a)
b = np.arange(3).reshape(3, 1)
print(b)
np.broadcast_arrays(a, b)

[0 1 2]
[[0]
 [1]
 [2]]


[array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]), array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])]

公式ドキュメント：https://numpy.org/doc/stable/reference/generated/numpy.broadcast_arrays.html

In [5]:
x = np.array([[1,2,3]])
y = np.array([[4],[5]])
np.broadcast_arrays(x, y)

[array([[1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5]])]

In [6]:
[np.array(a) for a in np.broadcast_arrays(x, y)] # 内包表記

[array([[1, 2, 3],
        [1, 2, 3]]), array([[4, 4, 4],
        [5, 5, 5]])]

## 5. 配列の演算

### 33. 一般的な四則演算  
a = np.array([1, 2, 3])  
b = np.array([4, 5, 6])  
において、足し算、引き算、掛け算、割り算を行え。また、aの３乗をしろ。

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a**3)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[ 1  8 27]


### 34. np.add(a, b) 
a, bの足し算  
a = np.array([1, 2, 3])  
b = np.array([4, 5, 6])  
のt足し算をnp.subtract()で行え。

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.add(a,b)

array([5, 7, 9])

### 35. np.subtract(a, b)
a, bの引き算  
a = np.array([1, 2, 3])  
b = np.array([4, 5, 6])  
の引き算をnp.subtract()で行え。

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.subtract(a, b)

array([-3, -3, -3])