# 【超初心者向け】Numpy基礎50本ノック

https://qiita.com/moe_713/items/671c8c912f6e8d6c7442?fbclid=IwAR02kecyHTdg8psjwYgveBXLbv9fYoUMxTlFQPV4Yyahi9cVWWcGEn82Q-U

In [1]:
import numpy as np

## 1.配列を作る

### 01. np.array  
1,2,3 を要素に持つnumpy配列を作れ

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
# リストを先に定義する
lst = [1, 2, 3]
np.array(lst)

array([1, 2, 3])

### 02. np.zeros
要素数が３つで全ての要素がゼロの配列を作れ

In [4]:
np.zeros(3, dtype=float)

array([0., 0., 0.])

公式ドキュメント  
https://numpy.org/doc/stable/reference/generated/numpy.zeros.html  
numpy.zeros(shape, dtype=float, order='C', *, like=None)

In [5]:
# Examples
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [7]:
np.zeros((2, 1)) # 2次元配列で要素が１つ

array([[0.],
       [0.]])

In [9]:
s = (2,2)
np.zeros(s)

array([[0., 0.],
       [0., 0.]])

In [10]:
np.zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')]) # custom dtype

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

### 03. np.zeros_like
以下のaと同じ形式の、要素がゼロの行列を作れ  
a = np.array([1, 2, 3])

In [13]:
a = np.array([1, 2, 3])
np.zeros_like(a) 

array([0, 0, 0])

公式ドキュメント  
https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html?highlight=zeros_like#numpy.zeros_like  
numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)

### 04. np.ones  
要素数が３つで全ての要素が1の配列を作れ

In [12]:
np.ones(3)

array([1., 1., 1.])

公式ドキュメント  
https://numpy.org/doc/stable/reference/generated/numpy.ones.html?highlight=ones  
numpy.ones(shape, dtype=None, order='C', *, like=None)

In [14]:
# Example
s = (2,2)
np.ones(s)

array([[1., 1.],
       [1., 1.]])

### 05. np.eye  
10x10の単位行列を作れ

単位行列(identity matrix)  
https://ja.wikipedia.org/wiki/%E5%8D%98%E4%BD%8D%E8%A1%8C%E5%88%97#:~:text=%E6%95%B0%E5%AD%A6%E3%80%81%E7%89%B9%E3%81%AB%E7%B7%9A%E5%9E%8B%E4%BB%A3%E6%95%B0%E5%AD%A6,%E5%85%83%E3%81%AE%E3%81%93%E3%81%A8%E3%81%A7%E3%81%82%E3%82%8B%E3%80%82  
https://en.wikipedia.org/wiki/Identity_matrix

In [16]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

公式ドキュメント  
https://numpy.org/doc/stable/reference/generated/numpy.eye.html?highlight=eye#numpy.eye  
numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)  
Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [17]:
# Example
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

kint, optional  
Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.