# 【超初心者向け】Numpy基礎50本ノック

https://qiita.com/moe_713/items/671c8c912f6e8d6c7442?fbclid=IwAR02kecyHTdg8psjwYgveBXLbv9fYoUMxTlFQPV4Yyahi9cVWWcGEn82Q-U

In [1]:
import numpy as np

## 4. 配列を操作する

### 21. np.flip  
配列の要素を反対にする   
a = np.array([[1, 2 ,3],[4, 5, 6]])の配列の要素を反対にしろ。

In [2]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
np.flip(a)

array([[6, 5, 4],
       [3, 2, 1]])

In [3]:
# このようにスライスをとっても同様の出力
a[::-1,::-1]

array([[6, 5, 4],
       [3, 2, 1]])

### 22. ndarray.transpose  
配列を転置する   
a = np.array([[1, 2 ,3],[4, 5, 6]])を転置しろ。

In [4]:
a = np.array([[1, 2 ,3],[4, 5, 6]])
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

### 23. np.append  
配列に要素を追加 
a = np.array([1, 2, 3]) の (1) 末尾に4を追加しろ。(2) 先頭に0を追加しろ。

In [5]:
a = np.array([1, 2, 3])
np.append(a, 4) # 末尾に4を追加

array([1, 2, 3, 4])

In [6]:
np.append(0, a) # 先頭に０を追加

array([0, 1, 2, 3])

### 24. np.where   
条件を満たす要素を返す、あるいはTrue・Falseを判定する   
a = np.arange(6).reshape((2, 3)) において  
(1) a<3の場合True、そうでない場合Falseを返せ。  
(2) a<3を満たす要素の範囲を抽出

In [7]:
a = np.arange(6).reshape((2, 3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
np.where(a < 3, True, False) # a<3の場合True、そうでない場合Falseを返す

array([[ True,  True,  True],
       [False, False, False]])

In [9]:
np.where(a < 3) # a<3を満たす要素の範囲を抽出

(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))

### 25. np.all    
配列の要素が全て条件を満たすか否かを判定する  
    a = np.arange(6).reshape((2, 3)) の全ての要素において (1) a < 3 を判定しろ。(2) a < 6 を判定しろ。

In [10]:
a = np.arange(6).reshape((2, 3))
a

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
np.all(a < 3)

False

In [12]:
np.all(a < 6)

True